test_buffer_limit_bytes.py: Fix assertion producing an AttributeError
When some of the assertions fail in the test they create the error
message by doing `listener.name`. This causes the following error:
`AttributeError: 'dict' object has no attribute 'name'`

We need to write `listener['name']` instead to produce the actual
error.

Signed-off-by: Tomas Baltrunas <tomasb@arista.com>