diagd: Fix envoy validation TimeoutExpired error message
When envoy validation process is too long, the exception
subprocess.TimeoutExpired will be raised.
The error message is outputting e.output.
This value can be None, so the code has been changed to handle this
case.
Otherwise, the logging line will raise an exception:
TypeError: not all arguments converted during string formatting