py-list-deps: Include the filename when reporting a syntax error
As seen on https://github.com/emissary-ingress/emissary/runs/5117413780 :

    tools/bin/py-list-deps --no-include-dev python/ | tools/bin/write-ifchanged python/requirements.in
    Traceback (most recent call last):
      File "/home/runner/work/emissary/emissary/tools/bin/py-list-deps", line 227, in <module>
        deps = main(inputdirs=args.input_dir, include_dev=bool(args.include_dev))
      File "/home/runner/work/emissary/emissary/tools/bin/py-list-deps", line 219, in main
        deps = deps.union(deps_for_pyfile(inputdir, filepath))
      File "/home/runner/work/emissary/emissary/tools/bin/py-list-deps", line 187, in deps_for_pyfile
        imports = parse_imports(filepath)
      File "/home/runner/work/emissary/emissary/tools/bin/py-list-deps", line 87, in parse_imports
        for node in ast.parse(filecontent).body:
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
      File "<unknown>", line 541
        self.logger.info("random code edit, this is a test"))
                                                            ^
    SyntaxError: unmatched ')'

And, uh, I guess while we're at it, fail faster by setting pipefail in the
rule in main.mk

Signed-off-by: Luke Shumaker <lukeshu@datawire.io>
(cherry picked from commit fe6eadebf68ed53288d074774af087bbfabcd1cc)